name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout (Wajib untuk repo baru)
      - name: Checkout
        uses: actions/checkout@v3

      # Langkah 2: Bikin Ular
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Pratama-wisnu
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Langkah 3: Upload (Dengan perintah create_branch)
      - name: Push to GitHub
        uses: crazy-max/gh-action-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          create_branch: true  # <--- INI KUNCI SUKSESNYA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
